[package]
name = "pfmt"
version = "0.1.0"
authors = ["Michail Pevnev <mpevnev@gmail.com>"]
license = "GPL-3.0-or-later"

[dependencies]
num = "0.2.0"

[dev-dependencies]
galvanic-test = "0.1.0"
galvanic-assert = "0.8.0"
